version: '3.4'

services:
  olympicgames:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

