version: '3.4'

name: ms_cloud_experts

services:
  ms_olympicgames:
    image: olympicgames
    container_name: ms_olympicgames
    build:
      context: .
      dockerfile: OlympicGames/Dockerfile
    depends_on:
      - ms_mssql

  ms_identityservice:
    image: identityservice
    container_name: ms_identityservice
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    depends_on: 
      - ms_mongo

  ms_mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: ms_mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password

  ms_mongo:
    image: mongo
    container_name: ms_mongo
    volumes: 
      - ms_mongodbdata:/data/db

  ms_seq:
    image: datalust/seq
    container_name: ms_seq
    environment:
      - ACCEPT_EULA=Y 

volumes:
  ms_mongodbdata: