version: '3.4'

services:
  ms_olympicgames:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8081:80

  ms_identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8082:80
  
  ms_mssql:
    ports:
      - 1440:1433

  ms_mongo:
    ports:
      - 27017:27017
  
  ms_seq:
    ports:
      - 8083:80
